version: '2'
services:
  mongo2:
    image: mongo
    volumes:
      - /data/db:/data/db
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.4 
  mainserver2:
    build: .
    volumes:
      - ./MainServer:/app/MainServer
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.5
    env_file:
      - ../credentials.env
    depends_on:
      - mongo2
    restart: always

  verificationserver2:
    build: VerificationServer/.
    volumes:
      - ./VerificationServer:/app
    env_file:
      - ../credentials.env
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.6
    depends_on:
      - mongo2
    restart: always
  nginx:
    build: LoadBalancer/.
    ports:
      - "80:80"
      - "81:81"
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.7
    depends_on:
      - mainserver2
      - verificationserver2
networks:
  zejjibeckbr:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

