version: '2'
services:
  mainserver:
    build: .
    ports:
      - "3000:3000"
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.5
    env_file:
      - ../credentials.env

  verificationserver:
    build: VerificationServer/.
    ports:
      - "3001:3001"    
    env_file:
      - ../credentials.env
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.6

networks:
  zejjibeckbr:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

