version: '2'
services:
  mongo2:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.4
 
  mainserver2:
    build: .
    ports:
      - "3000:3000"
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.5
    env_file:
      - ../credentials.env
    depends_on:
      - mongo2

  verificationserver2:
    build: VerificationServer/.
    ports:
      - "3001:3001"    
    env_file:
      - ../credentials.env
    networks:
      zejjibeckbr:
        ipv4_address: 172.22.0.6
    depends_on:
      - mongo2

networks:
  zejjibeckbr:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

